- name: install packages
  become: true
  apt:
    name: "{{item}}"
    state: present
    update_cache: yes
  loop: "{{package_list_debian}}"
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu' or ansible_distribution == 'Pop!_OS'
- name: install packages
  become: true
  dnf:
    name: "{{item}}"
    state: present
    update_cache: yes
  loop: "{{package_list_redhat}}"
  when: ansible_distribution == 'Fedora'
