- name: install packages
  become: yes
  apt:
    name: "{{item}}"
    state: present
    update_cache: yes
  loop: "{{package_list}}"
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu' or ansible_distribution == 'Pop!_OS'
- name: install packages
  become: yes
  dnf:
    name: "{{item}}"
    state: present
    update_cache: yes
  loop: "{{package_list}}"
  when: ansible_distribution == 'Fedora'
