- name: check dotnet installation
  stat:
    path: "{{user_home}}/.dotnet/"
  register: dotnet_path
- name: download dotnet installation script
  get_url:
    url: https://dot.net/v1/dotnet-install.sh
    dest: ~/dotnet-install.sh
    mode: 0755
    owner: "{{user}}"
    group: "{{user}}"
  when: not dotnet_path.stat.exists
- name: run dotnet installation script
  command: "~/dotnet-install.sh --channel {{dotnet_version}}"
  when: not dotnet_path.stat.exists
- name: add dotnet to zsh $PATH
  become: true
  lineinfile:
    path: "{{user_home}}/.zshrc"
    line: "PATH=$PATH:{{user_home}}/.dotnet/"
- name: add dotnet to bash $PATH
  become: true
  lineinfile:
    path: "{{user_home}}/.bashrc"
    line: "PATH=$PATH:{{user_home}}/.dotnet/"
- name: remove dotnet install script
  file:
    path: ~/dotnet-install.sh
    state: absent
