- name: update all packages
  become: yes
  apt:
    update_cache: true
    upgrade: dist
    autoclean: yes
    autoremove: yes
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu' or ansible_distribution == 'Pop!_OS'
- name: update all packages
  become: yes
  dnf:
    name: "*"
    state: latest
    update_cache: true
  when: ansible_distribution == 'Fedora'
