- name: install zsh
  become: yes
  apt:
    name: zsh
    update_cache: true
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu' or ansible_distribution == 'Pop!_OS'
- name: install zsh
  become: yes
  dnf:
    name: zsh
    update_cache: true
  when: ansible_distribution == 'Fedora'
- name: change user shell to zsh
  become: yes
  user:
    name: "{{user}}"
    shell: /bin/zsh
- name: create zsh config
  file:
    state: touch
    path: "{{user_home}}/.zshrc"
