- name: check of oh-my-zsh is already installed and configured
  stat:
    path: '{{user_home}}/.oh-my-zsh'
  register: omzconfig
- name: get oh-my-zsh installer
  get_url:
    url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
    dest: '{{ohmyzsh_installer}}'
    mode: 0755
    owner: '{{user}}'
    group: '{{user}}'
  when: not omzconfig.stat.exists
- name: install oh-my-zsh
  command: '{{ohmyzsh_installer}}'
  when: not omzconfig.stat.exists
- name: change user shell to zsh
  become: yes
  user:
    name: '{{user}}'
    shell: /bin/zsh
- name: install p10k
  git: 
    repo: 'https://github.com/romkatv/powerlevel10k.git'
    dest:  '~/.oh-my-zsh/custom/themes/powerlevel10k'
    depth: 1
  when: not omzconfig.stat.exists
- name: install elessar theme
  copy:
    src: elessar.zsh-theme
    dest: ~/.oh-my-zsh/themes/elessar.zsh-theme
    mode: 0644
    owner: '{{user}}'
    group: '{{user}}'
- name: set p10k theme
  lineinfile:
    path: ~/.zshrc
    regexp: '^ZSH_THEME='
    line: 'ZSH_THEME="elessar"'
  when: not omzconfig.stat.exists
