- name: get oh-my-zsh installer
  get_url:
    url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
    dest: '{{ohmyzsh_installer}}'
    mode: 0755
    owner: '{{user}}'
    group: '{{user}}'
- name: ensure oh-my-zsh is not configured
  file: 
    path: ~/.oh-my-zsh
    state: absent
- name: install oh-my-zsh
  command: '{{omz_installer}}'
- name: change user shell to zsh 
  become: yes
  user:
    name: '{{user}}'
    shell: /bin/zsh
- name: install p10k
  git: 
    repo: 'https://github.com/romkatv/powerlevel10k.git'
    dest:  '~/.oh-my-zsh/custom/themes/powerlevel10k'
    depth: 1
- name: set p10k theme
  lineinfile:
    path: ~/.zshrc
    regexp: '^ZSH_THEME='
    line: 'ZSH_THEME="powerlevel10k/powerlevel10k"'
