- name: install nvm
  git:
    repo: https://github.com/nvm-sh/nvm.git
    version: v0.38.0
    dest: '{{user_home}}/.nvm'
- name: setup .*rc nvm dir variables
  lineinfile:
    path: '{{item.dest}}'
    state: present
    line: '{{item.line}}'
  with_items:
    # zsh
    - { dest: '{{user_home}}/.zshrc', line: 'export NVM_DIR="$HOME/.nvm"' }
    - { dest: '{{user_home}}/.zshrc', line: '[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"' }
    - { dest: '{{user_home}}/.zshrc', line: '[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"' }
    # bash
    - { dest: '{{user_home}}/.bashrc', line: 'export NVM_DIR="$HOME/.nvm"' }
    - { dest: '{{user_home}}/.bashrc', line: '[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"' }
    - { dest: '{{user_home}}/.bashrc', line: '[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"' }
