- name: check for .zshrc
  stat:
    path: '{{user_home}}/.zshrc'
  register: zshrc
- name: apply profile to .zshrc
  lineinfile:
    path: '{{user_home}}/.zshrc'
    insertbefore: BOF
    line: 'source ~/.profile'
    state: present
  when: zshrc.stat.exists
